# Generated by Django 3.2.5 on 2021-08-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('account_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(max_length=50)),
                ('currency', models.CharField(blank=True, max_length=5)),
                ('status', models.CharField(max_length=10)),
                ('datetime_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('flow_type', models.CharField(max_length=40)),
                ('parent_id', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_sub_category', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsDB',
            fields=[
                ('transaction_id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('datetime_stamp', models.DateTimeField()),
                ('type', models.CharField(max_length=20)),
                ('from_account', models.CharField(max_length=30)),
                ('to_account', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('sub_category', models.CharField(max_length=50, null=True)),
                ('from_amount', models.PositiveBigIntegerField(null=True)),
                ('from_currency', models.CharField(max_length=5, null=True)),
                ('to_amount', models.PositiveBigIntegerField(null=True)),
                ('to_currency', models.CharField(max_length=5, null=True)),
                ('fees', models.CharField(max_length=30, null=True)),
                ('exchange_rate', models.PositiveBigIntegerField(null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('attachments', models.FilePathField(allow_folders=True, null=True)),
                ('user_posted', models.CharField(max_length=40, null=True)),
                ('budget_id', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
