# Generated by Django 3.2.5 on 2021-08-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetsApp', '0002_auto_20210819_2236'),
        ('FinanceApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('AssetsApp.assets',),
        ),
    ]
