# Generated by Django 3.2.5 on 2021-08-18 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('parent_id', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_sub_category', models.BooleanField()),
                ('datetime_added', models.DateTimeField(default=datetime.datetime(2021, 8, 18, 20, 0, 25, 255087))),
            ],
        ),
    ]
