# Generated by Django 3.2.5 on 2021-08-19 20:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssetsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('class_term', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=5, null=True)),
                ('datetime_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_tablespace': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='AssetsCategories',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('parent_id', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_sub_category', models.BooleanField()),
                ('datetime_added', models.DateTimeField(default=datetime.datetime(2021, 8, 19, 22, 36, 40, 25650))),
            ],
            options={
                'db_tablespace': 'Assets',
            },
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='assets',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssetsApp.assetscategories'),
        ),
    ]
