# Generated by Django 3.2.5 on 2021-08-19 22:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AssetsApp', '0002_auto_20210819_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='sub_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='AssetsApp.assetscategories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetscategories',
            name='datetime_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 0, 12, 11, 147207)),
        ),
    ]
