# Generated by Django 3.2.5 on 2021-08-19 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetsApp', '0003_auto_20210820_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetscategories',
            name='comment',
        ),
        migrations.AddField(
            model_name='assetscategories',
            name='name',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assets',
            name='status',
            field=models.CharField(help_text='0 Is Inservice, 1 is Inactive and 3 Under Maintaince', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetscategories',
            name='datetime_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 20, 1, 11, 27, 632781)),
        ),
        migrations.AlterField(
            model_name='assetscategories',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='assetscategories',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='assetscategories',
            name='parent_id',
            field=models.ManyToManyField(null=True, related_name='_AssetsApp_assetscategories_parent_id_+', to='AssetsApp.AssetsCategories'),
        ),
    ]
